"""Sync .hbs templates back to Python string constants in AgentFoundation.

This utility converts Handlebars templates (.hbs) back to Python .format()-style
string constants, enabling .hbs files to serve as the authoritative source of truth
for prompt content while maintaining backward compatibility with consumers that use
Python .format() substitution.

Usage:
    python sync_templates.py [--dry-run] [--verify]

    --dry-run   Show what would change without writing files
    --verify    Run parity test after sync to validate round-trip fidelity

Conversion rules (.hbs → Python .format()):
    {{{variable}}}  →  {variable}     (Handlebars unescaped → Python format var)
    {               →  {{              (literal brace needs escaping in .format())
    }               →  }}              (literal brace needs escaping in .format())

Note: Structuring/Classification templates use domain_taxonomy which is dynamically
generated by format_taxonomy_for_prompt(). The sync utility preserves the raw template
constants; the wrapper functions (get_structuring_prompt, get_classification_prompt)
remain unchanged.
"""

import re
import sys
import argparse
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional


class TemplateMapping(NamedTuple):
    """Maps an .hbs template to its Python target."""
    hbs_path: str                # Relative path from this script's directory
    python_file: str             # Relative path to Python file from AgentFoundation prompts dir
    constant_name: str           # Name of the Python constant to update
    skip_sync: bool = False      # If True, skip this template (e.g., no Python counterpart)
    format_specs: Dict[str, str] = {}  # Variable → Python format spec (e.g., {"similarity": ":.3f"})


# Paths
SCRIPT_DIR = Path(__file__).resolve().parent


def _find_core_projects_root() -> Path:
    """Walk up from SCRIPT_DIR to find the directory containing AgentFoundation/."""
    current = SCRIPT_DIR
    for parent in current.parents:
        if (parent / "AgentFoundation").is_dir():
            return parent
    raise RuntimeError(
        f"Cannot find CoreProjects root (directory containing AgentFoundation/) "
        f"by walking up from {SCRIPT_DIR}"
    )


AGENT_FOUNDATION_PROMPTS = (
    _find_core_projects_root()
    / "AgentFoundation"
    / "src"
    / "agent_foundation"
    / "knowledge"
    / "ingestion"
    / "prompts"
)


# Template → Python constant mappings
MAPPINGS: List[TemplateMapping] = [
    TemplateMapping(
        hbs_path="main/Structuring.hbs",
        python_file="structuring_prompt.py",
        constant_name="STRUCTURING_PROMPT_TEMPLATE",
    ),
    TemplateMapping(
        hbs_path="main/Structuring.PiecesOnly.hbs",
        python_file="structuring_prompt.py",
        constant_name="PIECES_ONLY_PROMPT_TEMPLATE",
    ),
    TemplateMapping(
        hbs_path="main/Classification.hbs",
        python_file="structuring_prompt.py",
        constant_name="CLASSIFICATION_PROMPT_TEMPLATE",
    ),
    TemplateMapping(
        hbs_path="main/QueryDecomposition.hbs",
        python_file=None,  # Inline in agentic_retriever.py — manual sync only
        constant_name=None,
        skip_sync=True,
    ),
    TemplateMapping(
        hbs_path="judgment/DedupJudge.hbs",
        python_file="dedup_llm_judge.py",
        constant_name="DEDUP_LLM_JUDGE_PROMPT",
        format_specs={"similarity": ":.3f"},
    ),
    TemplateMapping(
        hbs_path="judgment/MergeExecution.hbs",
        python_file="merge_execution.py",
        constant_name="MERGE_EXECUTION_PROMPT",
    ),
    TemplateMapping(
        hbs_path="judgment/UpdateIntent.hbs",
        python_file="update_prompt.py",
        constant_name="UPDATE_INTENT_PROMPT",
    ),
    TemplateMapping(
        hbs_path="judgment/Validation.hbs",
        python_file="validation.py",
        constant_name="VALIDATION_PROMPT",
    ),
    TemplateMapping(
        hbs_path="judgment/SkillSynthesis.hbs",
        python_file="skill_synthesis.py",
        constant_name="SKILL_SYNTHESIS_PROMPT",
        format_specs={"avg_similarity": ":.3f"},
    ),
]


def hbs_to_python_format(hbs_content: str, format_specs: Optional[Dict[str, str]] = None) -> str:
    """Convert Handlebars template content to Python .format()-style string.

    Conversion steps:
    1. Strip {{!-- ... --}} comment block at the top
    2. Convert {{{variable}}} → {variable} (or {variable:.3f} if format_specs provided)
    3. Escape remaining literal { → {{ and } → }} for .format() compatibility

    The order matters: we must handle {{{var}}} before escaping literal braces,
    otherwise the conversion would double-escape.

    Args:
        hbs_content: Raw Handlebars template content.
        format_specs: Optional dict mapping variable names to Python format specs
                      (e.g., {"similarity": ":.3f"}). These are appended to the
                      variable in the Python .format() output since Handlebars
                      has no equivalent of Python format specs.
    """
    format_specs = format_specs or {}

    # Step 1: Strip leading Handlebars comment
    content = re.sub(r"^\s*\{\{!--.*?--\}\}\s*", "", hbs_content, count=1, flags=re.DOTALL)

    # Step 2: Extract {{{variable}}} placeholders and replace with temporary markers
    # We use a marker that won't appear in normal text
    placeholders: Dict[str, str] = {}
    marker_idx = 0

    def replace_placeholder(match):
        nonlocal marker_idx
        var_name = match.group(1)
        marker = f"\x00PLACEHOLDER_{marker_idx}\x00"
        placeholders[marker] = var_name
        marker_idx += 1
        return marker

    content = re.sub(r"\{\{\{(\w+)\}\}\}", replace_placeholder, content)

    # Step 3: Escape literal braces for Python .format()
    content = content.replace("{", "{{").replace("}", "}}")

    # Step 4: Restore placeholders as Python .format() variables
    # Apply format specs where specified (e.g., similarity → similarity:.3f)
    for marker, var_name in placeholders.items():
        spec = format_specs.get(var_name, "")
        content = content.replace(marker, f"{{{var_name}{spec}}}")

    return content


def read_python_file(python_path: Path) -> str:
    """Read a Python file's content."""
    return python_path.read_text(encoding="utf-8")


def update_constant_in_python(
    python_content: str,
    constant_name: str,
    new_value: str,
) -> Optional[str]:
    """Replace a triple-quoted string constant in Python source code.

    Finds the constant assignment (e.g., PROMPT = \"\"\"...\"\"\") and replaces
    the string value while preserving surrounding code.

    Returns updated content, or None if constant not found.
    """
    # Match: CONSTANT_NAME = """..."""  (triple-quoted string)
    pattern = re.compile(
        rf'^({re.escape(constant_name)}\s*=\s*)(""".*?""")',
        re.MULTILINE | re.DOTALL,
    )

    match = pattern.search(python_content)
    if not match:
        return None

    prefix = match.group(1)  # e.g., 'DEDUP_LLM_JUDGE_PROMPT = '
    new_assignment = f'{prefix}"""{new_value}"""'
    return python_content[:match.start()] + new_assignment + python_content[match.end():]


def sync_template(mapping: TemplateMapping, dry_run: bool = False) -> bool:
    """Sync a single .hbs template to its Python constant.

    Returns True if sync succeeded (or no change needed), False on error.
    """
    if mapping.skip_sync:
        print(f"  SKIP {mapping.hbs_path} (manual sync only)")
        return True

    hbs_path = SCRIPT_DIR / mapping.hbs_path
    python_path = AGENT_FOUNDATION_PROMPTS / mapping.python_file

    if not hbs_path.exists():
        print(f"  ERROR {mapping.hbs_path}: .hbs file not found")
        return False

    if not python_path.exists():
        print(f"  ERROR {mapping.python_file}: Python file not found")
        return False

    # Read and convert (apply format specs for variables like similarity:.3f)
    hbs_content = hbs_path.read_text(encoding="utf-8")
    converted = hbs_to_python_format(hbs_content, format_specs=mapping.format_specs)

    # Read current Python file
    python_content = read_python_file(python_path)

    # Update constant
    updated = update_constant_in_python(python_content, mapping.constant_name, converted)
    if updated is None:
        print(f"  ERROR {mapping.constant_name}: constant not found in {mapping.python_file}")
        return False

    if updated == python_content:
        print(f"  OK {mapping.constant_name} (no change)")
        return True

    if dry_run:
        print(f"  WOULD UPDATE {mapping.constant_name} in {mapping.python_file}")
        return True

    python_path.write_text(updated, encoding="utf-8")
    print(f"  UPDATED {mapping.constant_name} in {mapping.python_file}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Sync .hbs templates to Python constants")
    parser.add_argument("--dry-run", action="store_true", help="Show changes without writing")
    parser.add_argument("--verify", action="store_true", help="Run parity test after sync")
    args = parser.parse_args()

    print(f"Syncing .hbs templates → Python constants")
    print(f"  Source: {SCRIPT_DIR}")
    print(f"  Target: {AGENT_FOUNDATION_PROMPTS}")
    print()

    if not AGENT_FOUNDATION_PROMPTS.exists():
        print(f"ERROR: Target directory not found: {AGENT_FOUNDATION_PROMPTS}")
        sys.exit(1)

    success = True
    for mapping in MAPPINGS:
        if not sync_template(mapping, dry_run=args.dry_run):
            success = False

    print()
    if args.dry_run:
        print("Dry run complete. No files were modified.")
    elif success:
        print("Sync complete.")
    else:
        print("Sync completed with errors.")

    if args.verify and not args.dry_run:
        print("\nRunning parity test...")
        from test_template_parity import run_parity_tests
        if not run_parity_tests():
            print("PARITY TEST FAILED — sync may have introduced differences")
            sys.exit(1)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
